
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || import.meta.env.NEXT_PUBLIC_SUPABASE_URL || "https://mxtsdgkwzjzlttpotole.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || import.meta.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im14dHNkZ2t3emp6bHR0cG90b2xlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxMDUyNTksImV4cCI6MjA2MjY4MTI1OX0.2KM8JxBEsqQidSvjhuLs8HCX-7g-q6YNswedQ5ZYq3g";

// Define the API endpoint that will be used for all backend services
// This will be used in a phased approach where api.seftec.store handles all backend services
const API_ENDPOINT = "https://api.seftec.store";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create Supabase client with error handling
let supabaseClient: any = null;

try {
  supabaseClient = createClient<Database>(
    SUPABASE_URL,
    SUPABASE_PUBLISHABLE_KEY,
    {
      auth: {
        autoRefreshToken: true,
        persistSession: true,
        detectSessionInUrl: true,
        flowType: "pkce",
        // Configure authentication callbacks
        // Note: Using object notation that's compatible with the Supabase types
        storage: {
          getItem: (key) => {
            try {
              const storedSession = localStorage.getItem(key);
              return storedSession;
            } catch (error) {
              console.error('Error getting session from storage:', error);
              return null;
            }
          },
          setItem: (key, value) => {
            try {
              localStorage.setItem(key, value);
            } catch (error) {
              console.error('Error storing session:', error);
            }
          },
          removeItem: (key) => {
            try {
              localStorage.removeItem(key);
            } catch (error) {
              console.error('Error removing session:', error);
            }
          }
        }
      },
      global: {
        // Configure custom fetch function to use the API endpoint for functions
        fetch: (...args) => {
          const [url, options] = args;

          // Check if this is a function invocation request (matches /functions/invoke)
          if (typeof url === 'string' && url.includes('/functions/invoke')) {
            // Replace the URL with the new API endpoint
            // This is temporary until the proper DNS configuration is in place
            const newUrl = url.replace(SUPABASE_URL, API_ENDPOINT);
            return fetch(newUrl, options);
          }

          // For all other requests, use the default fetch behavior
          return fetch(url, options);
        }
      }
    }
  );
} catch (error) {
  console.warn('Supabase client initialization failed:', error);
  // Create a mock client for development
  supabaseClient = {
    auth: {
      getSession: () => Promise.resolve({ data: { session: null }, error: null }),
      getUser: () => Promise.resolve({ data: { user: null }, error: null }),
      signOut: () => Promise.resolve({ error: null })
    },
    from: () => ({
      select: () => ({ single: () => Promise.resolve({ data: null, error: null }) }),
      insert: () => Promise.resolve({ data: null, error: null }),
      update: () => Promise.resolve({ data: null, error: null }),
      delete: () => Promise.resolve({ data: null, error: null })
    })
  };
}

export const supabase = supabaseClient;

// Helper functions for authentication
export const getCurrentUser = async () => {
  if (!supabase?.auth?.getSession) return null;

  const { data: { session }, error } = await supabase.auth.getSession();

  if (error) {
    console.error('Error getting session:', error);
    return null;
  }

  return session?.user || null;
};

export const getCurrentUserId = async () => {
  const user = await getCurrentUser();
  return user?.id || null;
};

export const getUserProfile = async () => {
  const userId = await getCurrentUserId();

  if (!userId || !supabase?.from) return null;

  try {
    const { data, error } = await supabase
      .from('profiles')
      .select('*')
      .eq('id', userId as string)
      .single();

    if (error) {
      console.error('Error fetching profile:', error);
      return null;
    }

    return data;
  } catch (error) {
    console.error('Error in getUserProfile:', error);
    return null;
  }
};
